import { OntResponse } from "../interfaces/ResponseOnt";



const listOnts: OntResponse[] = [
    {
        "_id": "646d02a1ccb8c77908e0ff1d",
        "oid": "null",
        "uid": "12",
        "valor": "null",
        "id_olt": 1,
        "id_metrica": 1,
        "fecha_poleo": new Date("2023-05-17T19:40:58.354+00:00"),
        "fecha_modificacion": new Date("2023-05-17T19:40:58.354+00:00"),
        "fecha_descubrimiento": new Date("2023-05-17T19:40:58.354+00:00"),
        "estatus": 1,
        "id_ejecucion": "null",
        "id_region": 1,
        "frame": 0,
        "slot": 1,
        "port": 5,
        "id_puerto": "null",
        "numero_serie": "sasaeasa",
        "tecnologia": "null",
        "index": "null",
        "indexFSP": "null",
        "descripcion": "null",
        "error": false,
        "alias": "null",
        "tipo": "null",
        "lastDownTime": "null",
        "descripcionAlarma": "test",
        "actualizacion": 1,
        "vip": 1,
        "sa": false,
        "inventario": true
    },
    {
        "_id": "6462fa3160f8463488618cc8",
        "oid": "null",
        "uid": "null",
        "valor": "null",
        "id_olt": 1,
        "id_metrica": 1,
        "fecha_poleo": new Date("2023-05-15T21:36:17.686+00:00"),
        "fecha_modificacion": new Date("2023-05-15T21:36:17.686+00:00"),
        "fecha_descubrimiento": new Date("2023-05-15T21:36:17.686+00:00"),
        "estatus": 1,
        "id_ejecucion": "null",
        "id_region": 6,
        "frame": 0,
        "slot": 4,
        "port": 6,
        "id_puerto": "null",
        "numero_serie": "464854549CED04C0",
        "tecnologia": "HUAWEI",
        "index": "null",
        "indexFSP": "null",
        "descripcion": "null",
        "error": false,
        "alias": "null",
        "tipo": "R",
        "lastDownTime": "---",
        "descripcionAlarma": "Estado Inicial",
        "actualizacion": 1,
        "vip": 1,
        "sa": false,
        "inventario": true
    },
    {
        "_id": "6463b6c760f84634886cd3b8",
        "oid": "null",
        "uid": "null",
        "valor": "null",
        "id_olt": 1,
        "id_metrica": 1,
        "fecha_poleo": new Date("2023-05-16T11:00:55.644+00:00"),
        "fecha_modificacion": new Date("2023-05-16T11:00:55.644+00:00"),
        "fecha_descubrimiento": new Date("2023-05-16T11:00:55.644+00:00"),
        "estatus": 1,
        "id_ejecucion": "null",
        "id_region": 6,
        "frame": 0,
        "slot": 2,
        "port": 0,
        "id_puerto": "null",
        "numero_serie": "48575443131511AB",
        "tecnologia": "HUAWEI",
        "index": "null",
        "indexFSP": "null",
        "descripcion": "null",
        "error": false,
        "alias": "null",
        "tipo": "R",
        "lastDownTime": "---",
        "descripcionAlarma": "Estado Inicial",
        "actualizacion": 1,
        "vip": 1,
        "sa": false,
        "inventario": true
    },

];

export default listOnts;