export class AppUrlSettings{

    public static BASE_API = 'http://10.180.199.75:9100/Totalplay/';
    //public static BASE_API = 'http://localhost:9081/';
    //public static BASE_API_LOGIN = 'http://localhost:9084/';
    //public static BASE_API_DESCUBRIMIENTO = 'http://localhost:9080/';
    //public static BASE_API = 'http://10.180.199.75:9081/';
    //public static BASE_API_DESCUBRIMIENTO = 'http://localhost:9082/';
    //public static BASE_API_LOGIN = 'http://10.180.199.75:9084/';
    public static BASE_API_LOGIN = 'http://localhost:9084/';
    //public static BASE_API = 'http://10.180.251.83:9081/';
    //public static BASE_API_DESCUBRIMIENTO = 'http://10.180.251.83:9080/';
    //public static BASE_API_LOGIN = 'http://10.180.251.83:9084/';
    public static GET_REGIONES = 'snmp-monitor/getRegion';
    public static GET_ONTS_BY_REGION = 'snmp-monitor/getOltsByRegion/';
    public static GET_ONTS_BY_OLTS_UP_DOWN= 'snmp-monitor/getOntsByOltsUp/';
    public static GET_ONTS_ALL= 'snmp-monitor/finOntsByIdAll/';
    public static GET_HISTORICO_CAMBIOS= 'snmp-monitor/getHistoricoCambios/';
    public static GET_TOTALES_TECNOLOGIA= 'snmp-monitor/getTotalesByTecnologia/';
    public static GET_TOTALES_ACTIVO= 'snmp-monitor/getTotalesActivo/';
    public static GET_TOTALES_BY_OLT= 'snmp-monitor/getTotalesByOlt/';
    public static GET_NAME_OLT= 'snmp-monitor/getNombreByRegex/';
    public static GET_ALIAS_ONT= 'snmp-monitor/getAliasByRegex/';
    public static GET_IP_OLT= 'snmp-monitor/getIpByRegex/';
    public static GET_SERIE_ONT= 'snmp-monitor/getSerieByRegex/';
    public static GET_REGEX_ACTUALIZACION= 'snmp-monitor/getRegexActualizacion/';
    public static GET_ONT_DETALLE_ACT= 'snmp-monitor/getOntDetalleAc/';
    public static FIND_OLT= 'snmp-monitor/findOlt';
    public static FIND_ONT= 'snmp-monitor/findOnt';
    public static GET_DETALLE_ACTUALIZACION= 'snmp-monitor/getDetalleActualizacion/';
    public static GET_DETALLE_ACTUALIZACION_DATA= 'snmp-monitor/getDetalleActuacionData/'
    public static GET_DETALLE_ACTUALIZACION_SERIE= 'snmp-monitor/getDetalleActuacionSerie/'
    public static GET_METRICAS= 'snmp-monitor/getMetrics/';
    public static GET_OLTS= 'snmp-monitor/getOlts/';
    public static UPDATE_STATUS="snmp-monitor/actualizaEstatus/";
    public static VALIDA_USUARIO="snmp-monitor/validaUser/";
    public static LOGIN ="login-lpda/login"
    public static GET_IP ="login-lpda/getIp"
    public static LOGOUT ="login-lpda/logout/"
    public static UPDATE_ESTATUS_OLT ="snmp-monitor/updateStatusOlt/"
    public static DESCUBRIMIENTO_MANUAL ="snmpv2/descubrimientoManual"
    public static POLEO_METRICAS_MANUAL="snmpv2/poleoMetricasManual/"
    public static VALIDA_MAXIMO ="snmp-monitor/validaMaximoDescunbrimiento"
    public static DETALLE_DES_MANUAL ="snmp-monitor/getDetalleDescubrimiento"
    public static DETALLES_METRICAS ="snmp-monitor/configmetric"
    public static CAMBIA_BLOQUE_METRICA="snmp-monitor/changeMetricBlock/"
    public static DESASIGNA_BLOQUE_METRICA="snmp-monitor/removeMetricBlock/"
    public static GET_ARCHIVO="snmp-monitor/getArchivo";
    public static POLEO_METRICA_OID="snmpv2/metrica/poleo"
    public static CAMBIOS="snmp-monitor/api/v2/limpieza/onts/repetidas/"
    public static ACTUALIZA_OLT_BY_ONT="snmp-monitor/actualizaOltOnOnt/"
    public static GET_RECHAZADOS_NCE= 'snmp-monitor/getSinActualizar'
    public static GET_RECHAZADAS_OLT='snmp-monitor/getRechazadasByOlt';
    public static GET_RECHAZADAS_OLT_NCE ='descubrimientoNCE';
    public static GET_RECHAZADOS_INVENTARIO_FINAL = 'snmp-monitor/getRechazadasByOltInventario';
    public static MOVER_ONT_INVENTARIO_FINAL = 'snmp-monitor/insertInventario';
}

