package totalplay.login.com.negocio.utils;

public enum LDAPCode {

	LDAP_0("LDAP_SUCCESS"),
	LDAP_1("LDAP_OPERATIONS_ERROR"),
	LDAP_2("LDAP_PROTOCOL_ERROR"),
	LDAP_3("LDAP_TIMELIMIT_EXCEEDED"),
	LDAP_4("LDAP_SIZELIMIT_EXCEEDED"),
	LDAP_5("LDAP_COMPARE_FALSE"),
	LDAP_6("LDAP_COMPARE_TRUE"),
	LDAP_7("LDAP_AUTH_METHOD_NOT_SUPPORTED"),
	LDAP_8("LDAP_STRONG_AUTH_REQUIRED"),
	LDAP_9("LDAP_PARTIAL_RESULTS"),
	LDAP_10("LDAP_REFERRAL"),
	LDAP_11("LDAP_ADMINLIMIT_EXCEEDED"),
	LDAP_12("LDAP_UNAVAILABLE_CRITICAL_EXTENSION"),
	LDAP_13("LDAP_CONFIDENTIALITY_REQUIRED"),
	LDAP_14("LDAP_SASL_BIND_IN_PROGRESS"),
	LDAP_16("LDAP_NO_SUCH_ATTRIBUTE"),
	LDAP_17("LDAP_UNDEFINED_TYPE"),
	LDAP_18("LDAP_INAPPROPRIATE_MATCHING"),
	LDAP_19("LDAP_CONSTRAINT_VIOLATION"),
	LDAP_20("LDAP_TYPE_OR_VALUE_EXISTS"),
	LDAP_21("LDAP_INVALID_SYNTAX"),
	LDAP_32("LDAP_NO_SUCH_OBJECT"),
	LDAP_33("LDAP_ALIAS_PROBLEM"),
	LDAP_34("LDAP_INVALID_DN_SYNTAX"),
	LDAP_35("LDAP_IS_LEAF"),
	LDAP_36("LDAP_ALIAS_DEREF_PROBLEM"),
	LDAP_48("LDAP_INAPPROPRIATE_AUTH"),
	LDAP_49("LDAP_INVALID_CREDENTIALS"),
	LDAP_50("LDAP_INSUFFICIENT_ACCESS"),
	LDAP_51("LDAP_BUSY"),
	LDAP_52("LDAP_UNAVAILABLE"),
	LDAP_53("LDAP_UNWILLING_TO_PERFORM"),
	LDAP_54("LDAP_LOOP_DETECT"),
	LDAP_64("LDAP_NAMING_VIOLATION");
	private String code;

	LDAPCode(String code) {
        this.code = code;
    }

    public String msgCode() {
        return code;
    }
}